#SPDX-License-Identifier: MIT-0
---
# tasks file for webserver_config
- name: Install Python 3
  package:
    name: python3
    state: present

- name: Install Apache
  become: true
  package:
    name: httpd
    state: present
  # delegate_to: "{{ item }}"
  # with_items: 
  #   - " groups[ 'dynamic_hosts' ] "
  # vars:
  #   ansible_ssh_private_key_file: 
  #   ansible_user: ec2-user
  # when: groups['dynamic_hosts'] is defined and goups['dynamic_hosts'] | length>0

- name: Start apache service on ec2 service
  become : true
  service: 
    name: httpd
    state: started
    enabled: yes