#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install common packages
  become: true
  package: 
    name:
      - httpd
      - nodejs
      - npm
    state: present

- name: Start and Enable Apache
  become: true
  service: 
    name: httpd
    state: started
    enabled: yes

- name: Ensure target directory exists
  become: true
  file:
    path: /opt/todo-app
    state: directory
    mode: '0755'

- name: Copy Source Code
  become: true
  synchronize:
    src: "{{ playbook_dir }}/../.."
    dest: "/opt/todo-app/todo-backend"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"