#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install common packages
  become: true
  ansible.builtin.package: 
    name:
      - httpd
      - nodejs
      - npm
    state: present

- name: Start and Enable Apache
  become: true
  ansible.builtin.service: 
    name: httpd
    state: started
    enabled: yes

- name: Ensure target directory exists
  become: true
  ansible.builtin.file:
    path: /opt/todo-app
    state: directory
    mode: '0755'

- name: Copy Source Code
  become: true
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../../todo-backend"
    dest: "/opt/todo-app/todo-backend"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"
    register: sync_result

- name: Trigger handler if source code changed
  become: true
  ansible.builtin.command: /bin/true # 2. Use a dummy command that does nothing
  changed_when: false
  when: sync_result.changed # 3. Run this task ONLY when the sync task reported a change
  notify: Restart Backend # 4. Notify the handler from this task