#SPDX-License-Identifier: MIT-0
---
# tasks file for common
- name: Install Common packages
  become: true
  package: 
    name:
      - httpd
      - nodejs
      - npm
  state: present

- name: Start and Enable Apache
  become: true
  service: 
    name: httpd
    state: started
    enabled: yes

- name: Copy Source Code
  become: true
  synchronize:
    src: "{{ playbook_dir }}/../../"
    dest: "/opt/todo-app"
    delete: yes
    recursive: yes
    resync_opts:
      - "--exclude=.git"
      - "--exclude=.github"
      - "--exclude=ansible"