---
- name: Provision EC2 instance & install XX
  hosts: localhost
  # vars:
  #   ansible_python_interpreter: /home/anshuman/.ansible_venv/bin/python
  roles: 
    - ec2_launch
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  gather_facts: false

- name: Configuration of EC2 instances
  hosts: launched_ec2_instances
  gather_facts: true
  roles:
    - common
    - frontend
    - backend

  