#SPDX-License-Identifier: MIT-0
---
# tasks file for frontend
- name: Install frontend dependencies
  become: true
  npm: 
    path: /opt/todo-app/todo-frontend
    state: present


- name: Build frontend
  become: true
  command: npm run build
  args:
    chdir: /opt/todo-app/todo-frontend

- name: Install PM2 globally
  become: true
  npm: 
    name: pm2
    global: yes