---
name: Provision of EC2 Instance and configuration with ansible
on:
    push:
        branches:
            - main

jobs:
 provision_of_ec2:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repo 
     uses: actions/checkout@v2

   - name: Setup Python 3.x
     uses: actions/setup-python@v2
     with:
        python-version: "3.10"

   - name: Install dependencies
     run: |
       python -m pip install --upgrade pip
       pip install ansible boto3
       ansible-galaxy collection install amazon.aws

   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_ID }}
        aws-region: ap-south-1

   - name: Create SSH key file
     run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
      chmod 600 ~/.ssh/ec2_key.pem

   - name: Debug SSH key
     run: ls -l ~/.ssh/ec2_key.pem

   - name: Run Ansible playbook
     run: |
      ansible-playbook ansible/playbooks/provision_and_configure_server.yml \
      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem"

     env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_ID }}
      AWS_SECRET_ACCESS_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY_PATH: ~/.ssh/ec2_key.pem
      ANSIBLE_HOST_KEY_CHECKING: false 



